### ISSUE TITLE
How about nested components?

### ISSUE THREAD

**Issue by libary** [torhovland/flatware#3]
Will it works? I would like to get an example. Thanks!

**Comment by torhovland** [comment]
That's a good point. I've added another Counter as a nested component inside FetchData, with just one line of code. You will find that both Counters cooperate on the same state. This is actually a good demonstration of the purpose of state management, because when you do this in vanilla Blazor, the Counters become independent.

**Comment by libary** [comment]
How about nested components with shared model?

**Comment by torhovland** [comment]
@libary That should work the same way. You can actually choose if you want to make the children into ReduxComponents of their own so they can access the model directly, or whether you want to flow data to the children using properties.
