### ISSUE TITLE
Interest in a component DSL?

### ISSUE THREAD

**Issue by panesofglass** [torhovland/flatware#5]
I’ve been working on a component DSL at https://github.com/panesofglass/blazorapp/tree/feature/fsharp-dsl/. Would you be interested in my contributing that to this project? I’m happy to collaborate on making it fit better with the goals of your project. Might also be worth keeping them separate. Thoughts?

**Comment by torhovland** [comment]
Hi!

I just looked at your Trail project. Looks cool! And fun to see how you've made it work with Flatware! Flatware has also moved on, and is now a proper Redux library with support for both F# and C#. It will be maintained on https://github.com/torhovland/blazor-redux from now on.

I think it makes sense to keep our projects separate, because folks may want to use Trail without Redux and vice versa. But we should definitely make sure they play nicely together. Feel free to submit PRs and issues in that regard. Just keep in mind that Blazor-Redux also needs to play nicely with C#.
